server:
  port: 8686
  servlet:
    context-path: /api



spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/rollingFoodsDB?createDatabaseIfNotExist=true"
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  Debug:
    logging:
      level:
        org:
            hibernate:
                SQL: DEBUG
                type: TRACE
            org:
            springframework:
                data:
                jpa:
                    repository:
                    query: DEBUG