server:
  port: 8686
  address: 0.0.0.0
  servlet:
    context-path: /api




spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/rollingFoodsDB?createDatabaseIfNotExist=true"
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-loactions: file:///D:/Projet rollingFoodsApp/pictures/
      static-path-pattern: /images/**

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  Debug:
    logging:
      level:
        org:
            hibernate:
                SQL: DEBUG
                type: TRACE
            org:
            springframework:
                data:
                jpa:
                    repository:
                    query: DEBUG

  mail:
    username: "f20161d96baaa6"
    password: "d3d74bc7044d71"
    host: "sandbox.smtp.mailtrap.io"
    port: 2525
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
  file:
    upload-dir: D:/Projet rollingFoodsApp/pictures


